// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwiftMessageProcessor.Infrastructure.Data;

#nullable disable

namespace SwiftMessageProcessor.Infrastructure.Migrations
{
    [DbContext(typeof(SwiftMessageContext))]
    [Migration("20251103132404_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SwiftMessageProcessor.Infrastructure.Entities.ProcessedMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("NTEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("NTEXT");

                    b.Property<string>("ParsedData")
                        .HasColumnType("NTEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("NTEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("MessageType")
                        .HasDatabaseName("IX_Messages_MessageType");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_Messages_ProcessedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Messages_Status");

                    b.HasIndex("MessageType", "ProcessedAt")
                        .HasDatabaseName("IX_Messages_Type_ProcessedAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("SwiftMessageProcessor.Infrastructure.Entities.SystemAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventData")
                        .HasColumnType("NTEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_SystemAudit_EventType");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SystemAudit_Timestamp");

                    b.ToTable("SystemAudit", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
